services:
  # Web service
  - type: web
    name: heart-disease-prediction
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0